import os
import pandas as pd

from dotenv import load_dotenv
from groq import Groq

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from utils import preprocess

# Load .env file
load_dotenv()

# Groq Client
client = Groq(api_key=os.getenv("GROQ_API_KEY"))


class FAQChatbot:

    def __init__(self, csv_file):

        self.data = pd.read_csv(csv_file)

        print("CSV Loaded Successfully")
        print("Total FAQs Loaded:", len(self.data))

        if "question" not in self.data.columns or "answer" not in self.data.columns:
            raise ValueError(
                "CSV file must contain 'question' and 'answer' columns."
            )

        # Clean Questions
        self.data["clean_question"] = self.data["question"].apply(preprocess)

        # TF-IDF Vectorizer
        self.vectorizer = TfidfVectorizer()

        self.question_vectors = self.vectorizer.fit_transform(
            self.data["clean_question"]
        )

    # ----------------------------------------------------
    # AI Answer using Groq
    # ----------------------------------------------------

    def ai_answer(self, question):

        try:

            response = client.chat.completions.create(

                model="llama-3.3-70b-versatile",

                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are a helpful AI assistant. "
                            "Give clear, short and accurate answers."
                        )
                    },
                    {
                        "role": "user",
                        "content": question
                    }
                ],

                temperature=0.4,
                max_tokens=500

            )

            return response.choices[0].message.content

        except Exception as e:

            return f"❌ AI Error: {str(e)}"

    # ----------------------------------------------------
    # Main Function
    # ----------------------------------------------------

    def get_answer(self, user_question):

        clean_query = preprocess(user_question)

        query_vector = self.vectorizer.transform([clean_query])

        similarity = cosine_similarity(
            query_vector,
            self.question_vectors
        )[0]

        top_indices = similarity.argsort()[-3:][::-1]

        best_index = top_indices[0]

        confidence = similarity[best_index]

        suggestions = []

        for idx in top_indices:

            suggestions.append({
                "question": self.data.iloc[idx]["question"],
                "score": float(similarity[idx])
            })

        # -----------------------------
        # FAQ Answer
        # -----------------------------

        if confidence >= 0.25:

            return {

                "answer": self.data.iloc[best_index]["answer"],

                "confidence": confidence,

                "matched_question": self.data.iloc[best_index]["question"],

                "suggestions": suggestions,

                "source": "FAQ"

            }

        # -----------------------------
        # AI Answer
        # -----------------------------

        ai_response = self.ai_answer(user_question)

        return {

            "answer": ai_response,

            "confidence": 1.0,

            "matched_question": "Generated by AI",

            "suggestions": suggestions,

            "source": "AI"

        }

    # ----------------------------------------------------

    def total_faqs(self):

        return len(self.data)